/// <reference types="@cloudflare/workers-types" />
import { GoogleGenerativeAI } from '@google/generative-ai'
import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { sign } from 'hono/jwt'
import { handle } from 'hono/cloudflare-pages'

type Bindings = {
  DB: D1Database
  KV: KVNamespace
  JWT_SECRET: string
  GEMINI_API_KEY: string
}

const app = new Hono<{ Bindings: Bindings }>().basePath('/api')

app.use('*', cors())

// Dashboard Stats
app.get('/stats', async (c) => {
  try {
    const studentsRes = await c.env.DB.prepare('SELECT COUNT(*) as count FROM students').first()
    const teachersRes = await c.env.DB.prepare('SELECT COUNT(*) as count FROM teachers').first()
    const schoolsRes = await c.env.DB.prepare('SELECT COUNT(*) as count FROM schools').first()
    
    return c.json({
      students: studentsRes?.count || 0,
      teachers: teachersRes?.count || 0,
      schools: schoolsRes?.count || 0,
      aiGenerations: 450 // Mocked for now
    })
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

// Auth routes
app.post('/auth/login', async (c) => {
  const body = await c.req.json()
  
  if (body.email && body.password) {
    let role = 'guru'
    let name = 'Guru'
    
    if (body.email.includes('super')) {
      role = 'super_admin'
      name = 'Super Admin'
    } else if (body.email.includes('admin')) {
      role = 'admin_sekolah'
      name = 'Admin Sekolah'
    }
    
    const payload = {
      email: body.email,
      role: role,
      exp: Math.floor(Date.now() / 1000) + 60 * 60 * 24, // 24 hours
    }
    
    const secret = c.env.JWT_SECRET || 'fallback-secret-for-dev'
    const token = await sign(payload, secret)
    return c.json({ token, name, role, email: body.email, user: { email: body.email, name, role } })
  }
  
  return c.json({ error: 'Invalid credentials' }, 401)
})

// Protected routes middleware
// app.use('/*', jwt({ secret: (c) => c.env.JWT_SECRET }))

app.get('/schools', async (c) => {
  try {
    const { results } = await c.env.DB.prepare('SELECT * FROM schools ORDER BY created_at DESC').all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/schools', async (c) => {
  try {
    const body = await c.req.json()
    // id is auto generated by standard UUID or frontend for simplicity we use crypto.randomUUID
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO schools (id, npsn, name, type, level, address, status) VALUES (?, ?, ?, ?, ?, ?, ?)'
    ).bind(id, body.npsn, body.name, body.type, body.level || 'SMA', body.address || '', body.status || 'active').run()
    
    return c.json({ message: 'School created successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to create school', details: error.message }, 500)
  }
})

app.put('/schools/:id', async (c) => {
  try {
    const id = c.req.param('id')
    const body = await c.req.json()
    
    await c.env.DB.prepare(
      'UPDATE schools SET npsn = ?, name = ?, type = ?, level = ?, address = ?, status = ? WHERE id = ?'
    ).bind(body.npsn, body.name, body.type, body.level || 'SMA', body.address || '', body.status || 'active', id).run()
    
    return c.json({ message: 'School updated successfully' })
  } catch (error: any) {
    return c.json({ error: 'Failed to update school', details: error.message }, 500)
  }
})

app.delete('/schools/:id', async (c) => {
  try {
    const id = c.req.param('id')
    await c.env.DB.prepare('DELETE FROM schools WHERE id = ?').bind(id).run()
    return c.json({ message: 'School deleted successfully' })
  } catch (error: any) {
    return c.json({ error: 'Failed to delete school', details: error.message }, 500)
  }
})

// Students routes
app.get('/students', async (c) => {
  try {
    const { results } = await c.env.DB.prepare(`
      SELECT s.*, sc.name as school_name 
      FROM students s 
      LEFT JOIN schools sc ON s.school_id = sc.id 
      ORDER BY s.created_at DESC
    `).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/students', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO students (id, school_id, nis, nisn, name, gender, status) VALUES (?, ?, ?, ?, ?, ?, ?)'
    ).bind(id, body.school_id || 'default-school', body.nis, body.nisn || '', body.name, body.gender || 'L', body.status || 'aktif').run()
    
    return c.json({ message: 'Student created successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to create student', details: error.message }, 500)
  }
})

app.put('/students/:id', async (c) => {
  try {
    const id = c.req.param('id')
    const body = await c.req.json()
    
    await c.env.DB.prepare(
      'UPDATE students SET nis = ?, nisn = ?, name = ?, gender = ?, status = ? WHERE id = ?'
    ).bind(body.nis, body.nisn || '', body.name, body.gender, body.status || 'aktif', id).run()
    
    return c.json({ message: 'Student updated successfully' })
  } catch (error: any) {
    return c.json({ error: 'Failed to update student', details: error.message }, 500)
  }
})

app.delete('/students/:id', async (c) => {
  try {
    const id = c.req.param('id')
    await c.env.DB.prepare('DELETE FROM students WHERE id = ?').bind(id).run()
    return c.json({ message: 'Student deleted successfully' })
  } catch (error: any) {
    return c.json({ error: 'Failed to delete student', details: error.message }, 500)
  }
})

// Teachers routes
app.get('/teachers', async (c) => {
  try {
    const { results } = await c.env.DB.prepare('SELECT * FROM teachers ORDER BY created_at DESC').all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/teachers', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO teachers (id, school_id, nip, nuptk, name, gender, phone, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'
    ).bind(id, body.school_id || 'default-school', body.nip, body.nuptk || '', body.name, body.gender || 'L', body.phone || '', body.status || 'aktif').run()
    
    return c.json({ message: 'Teacher created successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to create teacher', details: error.message }, 500)
  }
})

app.put('/teachers/:id', async (c) => {
  try {
    const id = c.req.param('id')
    const body = await c.req.json()
    
    await c.env.DB.prepare(
      'UPDATE teachers SET nip = ?, nuptk = ?, name = ?, gender = ?, phone = ?, status = ? WHERE id = ?'
    ).bind(body.nip, body.nuptk || '', body.name, body.gender, body.phone || '', body.status || 'aktif', id).run()
    
    return c.json({ message: 'Teacher updated successfully' })
  } catch (error: any) {
    return c.json({ error: 'Failed to update teacher', details: error.message }, 500)
  }
})

app.delete('/teachers/:id', async (c) => {
  try {
    const id = c.req.param('id')
    await c.env.DB.prepare('DELETE FROM teachers WHERE id = ?').bind(id).run()
    return c.json({ message: 'Teacher deleted successfully' })
  } catch (error: any) {
    return c.json({ error: 'Failed to delete teacher', details: error.message }, 500)
  }
})

// Academic Years routes
app.get('/academic-years', async (c) => {
  try {
    const { results } = await c.env.DB.prepare('SELECT * FROM academic_years ORDER BY created_at DESC').all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/academic-years', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    
    // If setting active, deactivate others first
    if (body.is_active) {
      await c.env.DB.prepare('UPDATE academic_years SET is_active = 0 WHERE school_id = ?').bind(body.school_id || 'default-school').run()
    }
    
    await c.env.DB.prepare(
      'INSERT INTO academic_years (id, school_id, name, semester, is_active) VALUES (?, ?, ?, ?, ?)'
    ).bind(id, body.school_id || 'default-school', body.name, body.semester, body.is_active ? 1 : 0).run()
    
    return c.json({ message: 'Academic Year created successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to create academic year', details: error.message }, 500)
  }
})

app.put('/academic-years/:id', async (c) => {
  try {
    const id = c.req.param('id')
    const body = await c.req.json()
    
    // If setting active, deactivate others first
    if (body.is_active) {
      await c.env.DB.prepare('UPDATE academic_years SET is_active = 0 WHERE school_id = ?').bind(body.school_id || 'default-school').run()
    }
    
    await c.env.DB.prepare(
      'UPDATE academic_years SET name = ?, semester = ?, is_active = ? WHERE id = ?'
    ).bind(body.name, body.semester, body.is_active ? 1 : 0, id).run()
    
    return c.json({ message: 'Academic Year updated successfully' })
  } catch (error: any) {
    return c.json({ error: 'Failed to update academic year', details: error.message }, 500)
  }
})

// Classes routes
app.get('/classes', async (c) => {
  try {
    const { results } = await c.env.DB.prepare(`
      SELECT c.*, t.name as teacher_name, ay.name as academic_year_name, ay.semester 
      FROM classes c 
      LEFT JOIN teachers t ON c.teacher_id = t.id 
      LEFT JOIN academic_years ay ON c.academic_year_id = ay.id
      ORDER BY c.level, c.name
    `).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/classes', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    
    await c.env.DB.prepare(
      'INSERT INTO classes (id, school_id, academic_year_id, teacher_id, name, level) VALUES (?, ?, ?, ?, ?, ?)'
    ).bind(id, body.school_id || 'default-school', body.academic_year_id, body.teacher_id, body.name, body.level).run()
    
    return c.json({ message: 'Class created successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to create class', details: error.message }, 500)
  }
})

app.put('/classes/:id', async (c) => {
  try {
    const id = c.req.param('id')
    const body = await c.req.json()
    
    await c.env.DB.prepare(
      'UPDATE classes SET academic_year_id = ?, teacher_id = ?, name = ?, level = ? WHERE id = ?'
    ).bind(body.academic_year_id, body.teacher_id, body.name, body.level, id).run()
    
    return c.json({ message: 'Class updated successfully' })
  } catch (error: any) {
    return c.json({ error: 'Failed to update class', details: error.message }, 500)
  }
})

app.delete('/classes/:id', async (c) => {
  try {
    const id = c.req.param('id')
    await c.env.DB.prepare('DELETE FROM classes WHERE id = ?').bind(id).run()
    return c.json({ message: 'Class deleted successfully' })
  } catch (error: any) {
    return c.json({ error: 'Failed to delete class', details: error.message }, 500)
  }
})

// Grades routes
app.get('/grades', async (c) => {
  try {
    const classId = c.req.query('class_id')
    const subject = c.req.query('subject')
    
    let query = 'SELECT * FROM grades WHERE 1=1'
    const params: any[] = []
    
    if (classId) {
      query += ' AND class_id = ?'
      params.push(classId)
    }
    if (subject) {
      query += ' AND subject = ?'
      params.push(subject)
    }
    
    const { results } = await c.env.DB.prepare(query).bind(...params).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/grades', async (c) => {
  try {
    const body = await c.req.json()
    // Body is an array of grades: { student_id, score, type }
    const { school_id, academic_year_id, class_id, subject, grades } = body
    
    // Process in a transaction-like way, or just loop
    for (const grade of grades) {
      const id = crypto.randomUUID()
      // First check if grade exists to update it, or just insert
      const existing = await c.env.DB.prepare(
        'SELECT id FROM grades WHERE class_id = ? AND student_id = ? AND subject = ? AND type = ?'
      ).bind(class_id, grade.student_id, subject, grade.type).first()
      
      if (existing) {
        await c.env.DB.prepare('UPDATE grades SET score = ?, feedback = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?')
          .bind(grade.score, grade.feedback || '', existing.id).run()
      } else {
        await c.env.DB.prepare(
          'INSERT INTO grades (id, school_id, academic_year_id, class_id, student_id, subject, type, score, feedback) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'
        ).bind(id, school_id || 'default-school', academic_year_id, class_id, grade.student_id, subject, grade.type, grade.score, grade.feedback || '').run()
      }
    }
    
    return c.json({ message: 'Grades saved successfully' }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to save grades', details: error.message }, 500)
  }
})

// AI Endpoint
// AI Endpoint
app.post('/ai/generate-erp', async (c) => {
  const body = await c.req.json()
  const { type, jenjang, mapel, fase, materi, level, jumlahPg, jumlahIsian, jumlahEssay, extraPrompt } = body
  
  try {
    const genAI = new GoogleGenerativeAI(c.env.GEMINI_API_KEY)
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" })

    let prompt = ''
    if (type === 'soal') {
      prompt = `
        Anda adalah seorang pembuat soal profesional untuk kurikulum pendidikan di Indonesia.
        Buatkan kumpulan soal dengan kriteria berikut:
        - Jenjang: ${jenjang || 'SMA'}
        - Mata Pelajaran: ${mapel}
        - Fase/Kelas: ${fase || 'E'}
        - Materi/Capaian Pembelajaran: ${materi}
        - Level Kognitif: ${level}
        - Jumlah Pilihan Ganda: ${jumlahPg || 0}
        - Jumlah Isian Singkat: ${jumlahIsian || 0}
        - Jumlah Uraian/Essay: ${jumlahEssay || 0}

        Kembalikan HANYA respons dalam format JSON Array murni yang valid tanpa awalan markdown \`\`\`json. Format setiap objek di dalam array:
        {
          "tipe": "pilihan_ganda" | "isian" | "essay",
          "pertanyaan": "string",
          "pilihan": ["A. opsi", "B. opsi", "C. opsi", "D. opsi", "E. opsi"], // Hanya disertakan jika tipe adalah pilihan_ganda
          "jawaban_benar": "string", // Kunci jawaban untuk pilihan_ganda/isian, atau contoh jawaban ideal/poin utama untuk essay
          "pembahasan": "penjelasan mengapa jawaban tersebut benar atau pedoman penskoran essay"
        }
      `
    } else if (type === 'lkpd') {
      prompt = `
        Buatkan LKPD (Lembar Kerja Peserta Didik) profesional Indonesia dengan kriteria:
        - Jenjang: ${jenjang || 'SMA'}
        - Mata Pelajaran: ${mapel}
        - Fase/Kelas: ${fase || 'E'}
        - Materi: ${materi}

        Kembalikan HANYA respons dalam format JSON Object murni yang valid tanpa awalan markdown \`\`\`json. Format:
        {
          "judul": "string",
          "tujuan": ["string"],
          "aktivitas": "string",
          "langkah_kerja": ["string"],
          "refleksi": "string",
          "evaluasi": "string",
          "petunjuk_guru": "string"
        }
      `
    } else if (type === 'bahan_ajar') {
      prompt = `
        Buatkan Bahan Ajar lengkap Indonesia dengan kriteria:
        - Jenjang: ${jenjang || 'SMA'}
        - Mata Pelajaran: ${mapel}
        - Fase/Kelas: ${fase || 'E'}
        - Materi: ${materi}

        Kembalikan HANYA respons dalam format JSON Object murni yang valid tanpa awalan markdown \`\`\`json. Format:
        {
          "judul": "string",
          "materi_lengkap": "string",
          "ringkasan": "string",
          "latihan_soal": ["string"],
          "contoh_soal": ["string"]
        }
      `
    } else if (type === 'kisi_kisi') {
      prompt = `
        Buatkan Kisi-Kisi Soal Indonesia dengan kriteria:
        - Jenjang: ${jenjang || 'SMA'}
        - Mata Pelajaran: ${mapel}
        - Fase/Kelas: ${fase || 'E'}
        - Materi: ${materi}

        Kembalikan HANYA respons dalam format JSON Object murni yang valid tanpa awalan markdown \`\`\`json. Format:
        {
          "kompetensi_dasar": "string",
          "materi_pokok": "string",
          "indikator_soal": ["string"],
          "bentuk_soal": "string",
          "level_kognitif": "string"
        }
      `
    } else if (type === 'modul_ajar') {
      prompt = `
        Buatkan Modul Ajar Kurikulum Merdeka Indonesia dengan kriteria:
        - Jenjang: ${jenjang || 'SMA'}
        - Mata Pelajaran: ${mapel}
        - Fase/Kelas: ${fase || 'E'}
        - Materi: ${materi}

        Kembalikan HANYA respons dalam format JSON Object murni yang valid tanpa awalan markdown \`\`\`json. Format:
        {
          "identitas_umum": "string",
          "tujuan_pembelajaran": ["string"],
          "langkah_pembelajaran": ["string"],
          "asesmen": "string",
          "media_pembelajaran": ["string"]
        }
      `
    } else if (type === 'pesantren_hafalan') {
      prompt = `
        Buatkan panduan hafalan Kitab/Al-Qur'an Pesantren dengan kriteria:
        - Materi/Kitab: ${materi}
        - Catatan/Fokus: ${extraPrompt || 'Hafalan rutin'}

        Kembalikan HANYA respons dalam format JSON Object murni yang valid tanpa awalan markdown \`\`\`json. Format:
        {
          "kitab": "string",
          "bab_pasal": "string",
          "target_hafalan": "string",
          "metode_setoran": "string",
          "tips_hafalan": ["string"]
        }
      `
    } else {
      throw new Error('Tipe tidak didukung')
    }

    const result = await model.generateContent(prompt)
    const responseText = result.response.text()
    
    // Clean up potential markdown formatting from Gemini
    const cleanedText = responseText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
    const parsedData = JSON.parse(cleanedText)

    return c.json({
      status: 'success',
      data: parsedData
    })
  } catch (error: any) {
    console.error('AI Error:', error)
    return c.json({ status: 'error', message: error.message || 'Gagal generate AI' }, 500)
  }
})

// CBT Exams routes
app.get('/cbt/exams', async (c) => {
  try {
    const { results } = await c.env.DB.prepare('SELECT * FROM cbt_exams ORDER BY created_at DESC').all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/cbt/exams', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO cbt_exams (id, title, class_id, duration, date, token, status) VALUES (?, ?, ?, ?, ?, ?, ?)'
    ).bind(id, body.title, body.class_id, body.duration, body.date, body.token, body.status || 'Aktif').run()
    return c.json({ message: 'Exam created successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to create exam', details: error.message }, 500)
  }
})

app.put('/cbt/exams/:id', async (c) => {
  try {
    const id = c.req.param('id')
    const body = await c.req.json()
    await c.env.DB.prepare(
      'UPDATE cbt_exams SET title = ?, class_id = ?, duration = ?, date = ?, token = ?, status = ? WHERE id = ?'
    ).bind(body.title, body.class_id, body.duration, body.date, body.token, body.status || 'Aktif', id).run()
    return c.json({ message: 'Exam updated successfully' })
  } catch (error: any) {
    return c.json({ error: 'Failed to update exam', details: error.message }, 500)
  }
})

// Attendance routes
app.get('/kesiswaan/attendance', async (c) => {
  try {
    const { results } = await c.env.DB.prepare(`
      SELECT a.*, s.name as student_name 
      FROM attendance a 
      LEFT JOIN students s ON a.student_id = s.id 
      ORDER BY a.date DESC, s.name
    `).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/kesiswaan/attendance', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO attendance (id, date, student_id, class_id, status, info) VALUES (?, ?, ?, ?, ?, ?)'
    ).bind(id, body.date, body.student_id, body.class_id || 'default-class', body.status, body.info || '').run()
    return c.json({ message: 'Attendance recorded successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to record attendance', details: error.message }, 500)
  }
})

// Achievements routes
app.get('/kesiswaan/achievements', async (c) => {
  try {
    const { results } = await c.env.DB.prepare(`
      SELECT ac.*, s.name as student_name 
      FROM achievements ac 
      LEFT JOIN students s ON ac.student_id = s.id 
      ORDER BY ac.date DESC
    `).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/kesiswaan/achievements', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO achievements (id, student_id, title, date, type) VALUES (?, ?, ?, ?, ?)'
    ).bind(id, body.student_id, body.title, body.date, body.type).run()
    return c.json({ message: 'Achievement recorded successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to record achievement', details: error.message }, 500)
  }
})

// Violations routes
app.get('/kesiswaan/violations', async (c) => {
  try {
    const { results } = await c.env.DB.prepare(`
      SELECT v.*, s.name as student_name 
      FROM violations v 
      LEFT JOIN students s ON v.student_id = s.id 
      ORDER BY v.date DESC
    `).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/kesiswaan/violations', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO violations (id, student_id, type, point, date) VALUES (?, ?, ?, ?, ?)'
    ).bind(id, body.student_id, body.type, body.point || 0, body.date).run()
    return c.json({ message: 'Violation recorded successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to record violation', details: error.message }, 500)
  }
})

// Pesantren Hafalan routes
app.get('/pesantren/hafalan', async (c) => {
  try {
    const { results } = await c.env.DB.prepare(`
      SELECT h.*, s.name as student_name 
      FROM hafalan h 
      LEFT JOIN students s ON h.student_id = s.id 
      ORDER BY h.date DESC
    `).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/pesantren/hafalan', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO hafalan (id, student_id, kitab, juz, surah, status, date) VALUES (?, ?, ?, ?, ?, ?, ?)'
    ).bind(id, body.student_id, body.kitab, body.juz || '', body.surah || '', body.status || 'Lancar', body.date).run()
    return c.json({ message: 'Hafalan setoran saved successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to save setoran hafalan', details: error.message }, 500)
  }
})

// Pesantren Sorogan routes
app.get('/pesantren/sorogan', async (c) => {
  try {
    const { results } = await c.env.DB.prepare(`
      SELECT sr.*, s.name as student_name 
      FROM sorogan sr 
      LEFT JOIN students s ON sr.student_id = s.id 
      ORDER BY sr.created_at DESC
    `).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/pesantren/sorogan', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO sorogan (id, student_id, kitab, bab, catatan, ustadz) VALUES (?, ?, ?, ?, ?, ?)'
    ).bind(id, body.student_id, body.kitab, body.bab || '', body.catatan || '', body.ustadz || '').run()
    return c.json({ message: 'Sorogan saved successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to save sorogan', details: error.message }, 500)
  }
})

// SMK PKL routes
app.get('/smk/pkl', async (c) => {
  try {
    const { results } = await c.env.DB.prepare(`
      SELECT p.*, s.name as student_name 
      FROM smk_pkl p 
      LEFT JOIN students s ON p.student_id = s.id 
      ORDER BY p.created_at DESC
    `).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/smk/pkl', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO smk_pkl (id, student_id, company_name, duration, grade, status) VALUES (?, ?, ?, ?, ?, ?)'
    ).bind(id, body.student_id, body.company_name, body.duration || '3 Bulan', body.grade || 'A', body.status || 'Aktif').run()
    return c.json({ message: 'PKL saved successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to save PKL', details: error.message }, 500)
  }
})

// SMK Certifications routes
app.get('/smk/certifications', async (c) => {
  try {
    const { results } = await c.env.DB.prepare(`
      SELECT c.*, s.name as student_name 
      FROM smk_certifications c 
      LEFT JOIN students s ON c.student_id = s.id 
      ORDER BY c.created_at DESC
    `).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/smk/certifications', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO smk_certifications (id, student_id, cert_name, examiner, date, grade, status) VALUES (?, ?, ?, ?, ?, ?, ?)'
    ).bind(id, body.student_id, body.cert_name, body.examiner || 'BNSP', body.date, body.grade || 'A', body.status || 'Lulus').run()
    return c.json({ message: 'Certification saved successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to save certification', details: error.message }, 500)
  }
})

// School Finance routes
app.get('/finance', async (c) => {
  try {
    const { results } = await c.env.DB.prepare(`
      SELECT f.*, s.name as student_name 
      FROM school_finance f 
      LEFT JOIN students s ON f.student_id = s.id 
      ORDER BY f.date DESC
    `).all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/finance', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO school_finance (id, student_id, type, amount, date, status) VALUES (?, ?, ?, ?, ?, ?)'
    ).bind(id, body.student_id, body.type, body.amount, body.date, body.status || 'Belum Lunas').run()
    return c.json({ message: 'Finance entry saved successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to save finance entry', details: error.message }, 500)
  }
})

// Library Books routes
app.get('/library', async (c) => {
  try {
    const { results } = await c.env.DB.prepare('SELECT * FROM library_books ORDER BY created_at DESC').all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/library', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO library_books (id, title, author, isbn, stock) VALUES (?, ?, ?, ?, ?)'
    ).bind(id, body.title, body.author || '', body.isbn || '', body.stock || 1).run()
    return c.json({ message: 'Book saved successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to save book', details: error.message }, 500)
  }
})

// WA Broadcast routes
app.get('/wa/broadcasts', async (c) => {
  try {
    const { results } = await c.env.DB.prepare('SELECT * FROM wa_broadcasts ORDER BY sent_at DESC').all()
    return c.json(results)
  } catch (error: any) {
    return c.json({ error: 'Database error', details: error.message }, 500)
  }
})

app.post('/wa/broadcasts', async (c) => {
  try {
    const body = await c.req.json()
    const id = crypto.randomUUID()
    await c.env.DB.prepare(
      'INSERT INTO wa_broadcasts (id, message, recipient, status) VALUES (?, ?, ?, ?)'
    ).bind(id, body.message, body.recipient, 'Sent').run()
    return c.json({ message: 'Broadcast message logged successfully', id }, 201)
  } catch (error: any) {
    return c.json({ error: 'Failed to log broadcast', details: error.message }, 500)
  }
})

// Auto Rollover Route
app.post('/academic/rollover', async (c) => {
  try {
    // Basic automatic student rollover logic:
    // Update all active students' status or simulate a grade progression.
    // In a real system, we'd update class assignments, but let's increment active student details or simulate database logs.
    await c.env.DB.prepare("UPDATE students SET status = 'alumni' WHERE id IN (SELECT student_id FROM class_students cs JOIN classes c ON cs.class_id = c.id WHERE c.level IN ('12', '9', '6'))").run()
    
    // Log audit trail
    const auditId = crypto.randomUUID()
    await c.env.DB.prepare(
      "INSERT INTO audit_logs (id, action, details) VALUES (?, ?, ?)"
    ).bind(auditId, 'AUTO_ROLLOVER', 'Melakukan kenaikan kelas otomatis dan pembaruan status alumni siswa kelas akhir.').run()
    
    return c.json({ message: 'Rollover akademik berhasil dijalankan.' })
  } catch (error: any) {
    return c.json({ error: 'Failed to run rollover', details: error.message }, 500)
  }
})

// Database Backup Route
app.get('/database/backup', async (c) => {
  try {
    const tables = ['schools', 'students', 'teachers', 'classes', 'cbt_exams', 'school_finance', 'library_books']
    const backup: any = {}
    for (const table of tables) {
      try {
        const { results } = await c.env.DB.prepare(`SELECT * FROM ${table}`).all()
        backup[table] = results
      } catch (e) {
        backup[table] = []
      }
    }
    return c.json(backup)
  } catch (error: any) {
    return c.json({ error: 'Failed to backup database', details: error.message }, 500)
  }
})

export const onRequest = handle(app)
