name = "edu-platform"
compatibility_date = "2024-03-20"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "KV"
id = "xxx-kv-id"

[[d1_databases]]
binding = "DB"
database_name = "e-admin-db"
database_id = "4bfd3bb3-a73d-467e-9924-b2a38b07cce0"
